re #129 making production code again

diff --git a/Dockerfile.viewer b/Dockerfile.viewer
--- a/Dockerfile.viewer
+++ b/Dockerfile.viewer
@@ -14,11 +14,12 @@ RUN npm install
 COPY static/ ./
 RUN node -e "console.log('vite=', require('vite/package.json').version)" && [ -f vite.config.js ] || (echo 'vite.config.js missing' && exit 1)
 
-# This is for production
-#RUN npm run build && ls -la dist && [ -f dist/manifest.json ] || (echo 'manifest missing' && exit 2)
+# Choose one of these builds only:
 
+#This is for production
+RUN npm run build && ls -la dist && [ -f dist/manifest.json ] || (echo 'manifest missing' && exit 2)
 # This is for dev
-RUN npx vite build --minify=false --sourcemap && ls -la dist && [ -f dist/manifest.json ] || (echo 'manifest missing' && exit 2)
+#RUN npx vite build --minify=false --sourcemap && ls -la dist && [ -f dist/manifest.json ] || (echo 'manifest missing' && exit 2)
 
 
 
